import { ActividadesEconomicas } from './interfaces/actividades-economicas.interface';

export function actividadesEconomicas(): ActividadesEconomicas[] {
  return [
    {
      fechaCreacion: '2016-07-17T05:50:06.86',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 209,
      descripcion: 'Actividad bursátil',
      codigoActividadEconomica: 'J101',
      codigoCIIU: 209,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.85',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 201,
      descripcion: 'Actividades conexas  del servicio de transporte',
      codigoActividadEconomica: 'I90',
      codigoCIIU: 201,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.683',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 78,
      descripcion: 'Actividades conexas de pesca',
      codigoActividadEconomica: 'B069',
      codigoCIIU: 78,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.66',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 62,
      descripcion:
        'Actividades conexas de servicios agropecuarios, excepto las actividades  veterinarias',
      codigoActividadEconomica: 'A0619',
      codigoCIIU: 62,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.98',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 248,
      descripcion:
        'Actividades culturales,  deportivas y otras actividades de esparcimiento',
      codigoActividadEconomica: 'R24',
      codigoCIIU: 248,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.723',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 111,
      descripcion:
        'Actividades de edición e impresión y de reproducción de grabaciones',
      codigoActividadEconomica: 'D20',
      codigoCIIU: 111,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.197',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 298,
      descripcion: 'Actividades del sector privado externo',
      codigoActividadEconomica: 'Z04',
      codigoCIIU: 298,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.193',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 297,
      descripcion: 'Actividades del sector público externo',
      codigoActividadEconomica: 'Z02',
      codigoCIIU: 297,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.863',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 212,
      descripcion: 'Actividades inmobiliarias',
      codigoActividadEconomica: 'K02',
      codigoCIIU: 212,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.07',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 270,
      descripcion: 'Actividades no contempladas en ninguna otra actividad',
      codigoActividadEconomica: 'X90',
      codigoCIIU: 270,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.07',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 269,
      descripcion: 'Actividades productivas sin fines de lucro',
      codigoActividadEconomica: 'X04',
      codigoCIIU: 269,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.987',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 252,
      descripcion:
        'Actividades vinculadas al  turismo y no contempladas en otras otras actividades',
      codigoActividadEconomica: 'R32',
      codigoCIIU: 252,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.67',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 71,
      descripcion: 'Acuacultura y actividades de servicio conexas',
      codigoActividadEconomica: 'B04',
      codigoCIIU: 71,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.987',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 250,
      descripcion: 'Agencias de viaje e información  turística',
      codigoActividadEconomica: 'R28',
      codigoCIIU: 250,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.63',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 40,
      descripcion: 'Algodón',
      codigoActividadEconomica: 'A02181',
      codigoCIIU: 40,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.943',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 235,
      descripcion: 'Almacenamiento',
      codigoActividadEconomica: 'R06',
      codigoCIIU: 235,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.987',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 251,
      descripcion: 'Alquiler de autos',
      codigoActividadEconomica: 'R30',
      codigoCIIU: 251,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.837',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 191,
      descripcion: 'Alquiler de autos (a turistas)',
      codigoActividadEconomica: 'I0231',
      codigoCIIU: 191,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.863',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 213,
      descripcion: 'Alquiler de bienes no contemplados en otras actividades',
      codigoActividadEconomica: 'K04',
      codigoCIIU: 213,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.947',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 238,
      descripcion: 'Alquiler de maquinaria y equipo',
      codigoActividadEconomica: 'R12',
      codigoCIIU: 238,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.587',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 5,
      descripcion: 'Arroz',
      codigoActividadEconomica: 'A021101',
      codigoCIIU: 5,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.977',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 245,
      descripcion: 'Asesoría informática',
      codigoActividadEconomica: 'R222',
      codigoCIIU: 245,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.673',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 73,
      descripcion: 'Atún',
      codigoActividadEconomica: 'B061',
      codigoCIIU: 73,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.613',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 23,
      descripcion: 'Banano',
      codigoActividadEconomica: 'A0213102',
      codigoCIIU: 23,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.71',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 98,
      descripcion: 'Beneficio de arroz',
      codigoActividadEconomica: 'D0251',
      codigoCIIU: 98,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.71',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 99,
      descripcion: 'Beneficio de café',
      codigoActividadEconomica: 'D0252',
      codigoCIIU: 99,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.59',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 6,
      descripcion: 'Café',
      codigoActividadEconomica: 'A021102',
      codigoCIIU: 6,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.677',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 74,
      descripcion: 'Camarones',
      codigoActividadEconomica: 'B062',
      codigoCIIU: 74,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.6',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 14,
      descripcion: 'Camote',
      codigoActividadEconomica: 'A021153',
      codigoCIIU: 14,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.62',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 29,
      descripcion: 'Caña  de azúcar',
      codigoActividadEconomica: 'A0213301',
      codigoCIIU: 29,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.663',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 65,
      descripcion:
        'Caza, pieles y repoblación de animales de caza, incluyendo actividades  conexas',
      codigoActividadEconomica: 'A081',
      codigoCIIU: 65,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.983',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 249,
      descripcion:
        'Cinematografía, ratio, televisión y otras actividades de entretenimiento',
      codigoActividadEconomica: 'R26',
      codigoCIIU: 249,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.937',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 230,
      descripcion: 'Clínica y hospital',
      codigoActividadEconomica: 'R041',
      codigoCIIU: 230,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.817',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 174,
      descripcion:
        'Comercio al por mayor y  por comisión, excepto de vehículos de motor y  motocicletas',
      codigoActividadEconomica: 'G04',
      codigoCIIU: 174,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.817',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 175,
      descripcion:
        'Comercio al por menor, excepto de vehículos de motor, motocicletas y combustible automotriz',
      codigoActividadEconomica: 'G06',
      codigoCIIU: 175,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.813',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 173,
      descripcion:
        'Comercio de vehículos de motor y motocicletas; venta al detalle de combustible automotriz',
      codigoActividadEconomica: 'G02',
      codigoCIIU: 173,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.027',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 259,
      descripcion: 'Compra de menaje de casa',
      codigoActividadEconomica: 'S08',
      codigoCIIU: 259,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.787',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 155,
      descripcion: 'Compra de terreno para vivienda  (no incluye construcción)',
      codigoActividadEconomica: 'F0411',
      codigoCIIU: 155,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.023',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 257,
      descripcion: 'Compra de vehículos',
      codigoActividadEconomica: 'S04',
      codigoCIIU: 257,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.79',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 156,
      descripcion: 'Compra de vivienda nueva',
      codigoActividadEconomica: 'F0412',
      codigoCIIU: 156,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.79',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 157,
      descripcion: 'Compra de vivienda usada',
      codigoActividadEconomica: 'F0413',
      codigoCIIU: 157,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.797',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 158,
      descripcion: 'Compra y reparación de vivienda',
      codigoActividadEconomica: 'F0414',
      codigoCIIU: 158,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.14',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 285,
      descripcion: 'Conservación ambiental',
      codigoActividadEconomica: 'Y26',
      codigoCIIU: 285,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.78',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 151,
      descripcion: 'Construcción  de otros inmuebles',
      codigoActividadEconomica: 'F0229',
      codigoCIIU: 151,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.78',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 149,
      descripcion: 'Construcción de casas y/o  edificios',
      codigoActividadEconomica: 'F0221',
      codigoCIIU: 149,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.78',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 150,
      descripcion: 'Construcción de otros edificios comerciales',
      codigoActividadEconomica: 'F0226',
      codigoCIIU: 150,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.8',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 163,
      descripcion: 'Construcción de otros inmuebles con fines no comerciales',
      codigoActividadEconomica: 'F0429',
      codigoCIIU: 163,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.8',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 161,
      descripcion: 'Construcción de vivienda para uso del deudor',
      codigoActividadEconomica: 'F0421',
      codigoCIIU: 161,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.8',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 162,
      descripcion: 'Construcción de vivienda para uso no comercial de terceros',
      codigoActividadEconomica: 'F0422',
      codigoCIIU: 162,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.15',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 286,
      descripcion:
        'Construcción, administración y mantenimiento de infraestructura',
      codigoActividadEconomica: 'Y28',
      codigoCIIU: 286,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.943',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 236,
      descripcion: 'Correo',
      codigoActividadEconomica: 'R08',
      codigoCIIU: 236,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.647',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 52,
      descripcion: 'Cría de aves',
      codigoActividadEconomica: 'A0413',
      codigoCIIU: 52,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.65',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 53,
      descripcion: 'Cría de cabras y ovejas',
      codigoActividadEconomica: 'A0414',
      codigoCIIU: 53,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.65',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 55,
      descripcion: 'Cría de otros animales',
      codigoActividadEconomica: 'A0419',
      codigoCIIU: 55,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.65',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 54,
      descripcion: 'Cría y desarrollo de ganado doble propósito (carne/leche)',
      codigoActividadEconomica: 'A0418',
      codigoCIIU: 54,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.647',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 51,
      descripcion: 'Cría y desarrollo de ganado lechero',
      codigoActividadEconomica: 'A0412',
      codigoCIIU: 51,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.647',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 50,
      descripcion: 'Cría, desarrollo y engorde de ganado vacuno',
      codigoActividadEconomica: 'A0411',
      codigoCIIU: 50,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.63',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 38,
      descripcion: 'Cultivo de  otras plantas  y actividades  conexas',
      codigoActividadEconomica: 'A02149',
      codigoCIIU: 38,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.617',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 27,
      descripcion: 'Cultivo de especias',
      codigoActividadEconomica: 'A02132',
      codigoCIIU: 27,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.623',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 34,
      descripcion:
        'Cultivo de flores y plantas ornamentales  para vivero  (no para exportación)',
      codigoActividadEconomica: 'A02141',
      codigoCIIU: 34,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.627',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 35,
      descripcion:
        'Cultivo de flores y plantas ornamentales  para vivero  (para exportación)',
      codigoActividadEconomica: 'A02142',
      codigoCIIU: 35,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.607',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 19,
      descripcion:
        'Cultivo de hortalizas, legumbres y especialidades  hortícolas',
      codigoActividadEconomica: 'A021202',
      codigoCIIU: 19,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.66',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 61,
      descripcion:
        'Cultivo de productos agrícolas en combinación con la cría de animales (explotación mixta)',
      codigoActividadEconomica: 'A0611',
      codigoCIIU: 61,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.63',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 37,
      descripcion: 'Cultivo de productos de semillero.',
      codigoActividadEconomica: 'A02144',
      codigoCIIU: 37,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.607',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 18,
      descripcion: 'Cultivo de vegetales',
      codigoActividadEconomica: 'A021201',
      codigoCIIU: 18,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.627',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 36,
      descripcion: 'Cultivo y elaboración de  otros productos de vivero',
      codigoActividadEconomica: 'A02143',
      codigoCIIU: 36,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.153',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 288,
      descripcion: 'Cultura',
      codigoActividadEconomica: 'Y32',
      codigoCIIU: 288,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.717',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 106,
      descripcion:
        'Curtido y adobo de cueros y  pieles; fabricación de maletas, bolsos de mano, artículos de talabartería y guarnicionería (excepto calzado)',
      codigoActividadEconomica: 'D10',
      codigoCIIU: 106,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.153',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 289,
      descripcion: 'Deportes',
      codigoActividadEconomica: 'Y34',
      codigoCIIU: 289,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.98',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 246,
      descripcion: 'Desarrollo de  software',
      codigoActividadEconomica: 'R223',
      codigoCIIU: 246,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.947',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 237,
      descripcion:
        'Drenaje, eliminación de desperdicios y aguas residuales, saneamiento y actividades similares',
      codigoActividadEconomica: 'R10',
      codigoCIIU: 237,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.71',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 101,
      descripcion: 'Elaboración de bebidas',
      codigoActividadEconomica: 'D026',
      codigoCIIU: 101,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.72',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 107,
      descripcion: 'Elaboración de calzado',
      codigoActividadEconomica: 'D12',
      codigoCIIU: 107,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.7',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 93,
      descripcion: 'Elaboración de embutidos',
      codigoActividadEconomica: 'D0215',
      codigoCIIU: 93,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.707',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 96,
      descripcion:
        'Elaboración de productos alimenticios a base de frutas, legumbres y hortalizas',
      codigoActividadEconomica: 'D024',
      codigoCIIU: 96,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.703',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 95,
      descripcion: 'Elaboración de productos lácteos',
      codigoActividadEconomica: 'D023',
      codigoCIIU: 95,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.703',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 94,
      descripcion:
        'Elaboración y conservación de pescado  y productos de pescado',
      codigoActividadEconomica: 'D022',
      codigoCIIU: 94,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.097',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 277,
      descripcion: 'Electricidad',
      codigoActividadEconomica: 'Y10',
      codigoCIIU: 277,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.073',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 274,
      descripcion: 'Enseñanza',
      codigoActividadEconomica: 'Y04',
      codigoCIIU: 274,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.87',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 217,
      descripcion: 'Enseñanza Preescolar',
      codigoActividadEconomica: 'M02',
      codigoCIIU: 217,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.9',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 218,
      descripcion: 'Enseñanza primaria',
      codigoActividadEconomica: 'M04',
      codigoCIIU: 218,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.91',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 219,
      descripcion: 'Enseñanza primaria y secundaria',
      codigoActividadEconomica: 'M06',
      codigoCIIU: 219,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.91',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 222,
      descripcion: 'Enseñanza Técnica',
      codigoActividadEconomica: 'M12',
      codigoCIIU: 222,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.91',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 220,
      descripcion: 'Enseñanza universitaria y/o parauniversitaria',
      codigoActividadEconomica: 'M08',
      codigoCIIU: 220,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.68',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 76,
      descripcion: 'Escama y tuburón',
      codigoActividadEconomica: 'B064',
      codigoCIIU: 76,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.127',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 280,
      descripcion: 'Explotación de  minas y canteras',
      codigoActividadEconomica: 'Y16',
      codigoCIIU: 280,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.667',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 68,
      descripcion: 'Extracción de madera y actividades de servicio conexas',
      codigoActividadEconomica: 'A102',
      codigoCIIU: 68,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.69',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 84,
      descripcion:
        'Extracción de otras minas y canteras  y actividades de servicios conexas',
      codigoActividadEconomica: 'C04',
      codigoCIIU: 84,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.69',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 83,
      descripcion:
        'Extracción de petróleo crudo y gas natural y actividades de servicio conexas',
      codigoActividadEconomica: 'C02',
      codigoCIIU: 83,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.727',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 113,
      descripcion: 'Fabricación de sustancias y productos químicos',
      codigoActividadEconomica: 'D24',
      codigoCIIU: 113,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.59',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 8,
      descripcion: 'Frijol',
      codigoActividadEconomica: 'A021104',
      codigoCIIU: 8,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.17',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 294,
      descripcion: 'Gestión Electoral',
      codigoActividadEconomica: 'Y904',
      codigoCIIU: 294,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.17',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 293,
      descripcion: 'Gestión Judicial',
      codigoActividadEconomica: 'Y903',
      codigoCIIU: 293,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.163',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 291,
      descripcion: 'Gestión Legislativa',
      codigoActividadEconomica: 'Y901',
      codigoCIIU: 291,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.167',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 292,
      descripcion: 'Hacienda Pública',
      codigoActividadEconomica: 'Y902',
      codigoCIIU: 292,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.12',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 279,
      descripcion: 'Hidrocarburos',
      codigoActividadEconomica: 'Y14',
      codigoCIIU: 279,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.827',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 183,
      descripcion: 'Hotel',
      codigoActividadEconomica: 'H02',
      codigoCIIU: 183,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.83',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 185,
      descripcion: 'Hotel y restaurante',
      codigoActividadEconomica: 'H06',
      codigoCIIU: 185,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.853',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 204,
      descripcion:
        'Intermediación financiera, excepto seguros, pensiones y fondos de inversión',
      codigoActividadEconomica: 'J02',
      codigoCIIU: 204,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.13',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 281,
      descripcion:
        'Intermediación financiera, excepto seguros, pensiones y fondos de inversión',
      codigoActividadEconomica: 'Y18',
      codigoCIIU: 281,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.867',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 214,
      descripcion: 'Investigación y Desarrollo',
      codigoActividadEconomica: 'K06',
      codigoCIIU: 214,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.937',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 231,
      descripcion: 'Laboratorio clínico (no incluidos en hospital)',
      codigoActividadEconomica: 'R042',
      codigoCIIU: 231,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.96',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 241,
      descripcion: 'Lavandería',
      codigoActividadEconomica: 'R18',
      codigoCIIU: 241,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.597',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 11,
      descripcion: 'Macadamia',
      codigoActividadEconomica: 'A021107',
      codigoCIIU: 11,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.59',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 7,
      descripcion: 'Maíz',
      codigoActividadEconomica: 'A021103',
      codigoCIIU: 7,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.713',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 103,
      descripcion: 'Manufactura de   productos de tabaco',
      codigoActividadEconomica: 'D04',
      codigoCIIU: 103,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.74',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 121,
      descripcion: 'Manufactura de  otros aparatos eléctricos',
      codigoActividadEconomica: 'D40',
      codigoCIIU: 121,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.727',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 114,
      descripcion: 'Manufactura de caucho y  productos plásticos',
      codigoActividadEconomica: 'D26',
      codigoCIIU: 114,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.737',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 119,
      descripcion:
        'Manufactura de equipo de oficina, contabilidad e informática',
      codigoActividadEconomica: 'D36',
      codigoCIIU: 119,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.737',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 120,
      descripcion:
        'Manufactura de equipo y aparatos de radio, televisión y comunicaciones',
      codigoActividadEconomica: 'D38',
      codigoCIIU: 120,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.74',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 122,
      descripcion:
        'Manufactura de instrumentos médicos, de precisión,   ópticos y otros',
      codigoActividadEconomica: 'D42',
      codigoCIIU: 122,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.75',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 126,
      descripcion: 'Manufactura de instrumentos musicales',
      codigoActividadEconomica: 'D50',
      codigoCIIU: 126,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.733',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 118,
      descripcion: 'Manufactura de maquinaria y equipo de producción',
      codigoActividadEconomica: 'D34',
      codigoCIIU: 118,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.73',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 116,
      descripcion: 'Manufactura de metales comunes',
      codigoActividadEconomica: 'D30',
      codigoCIIU: 116,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.72',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 109,
      descripcion: 'Manufactura de muebles',
      codigoActividadEconomica: 'D16',
      codigoCIIU: 109,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.75',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 128,
      descripcion: 'Manufactura de otros productos',
      codigoActividadEconomica: 'D80',
      codigoCIIU: 128,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.713',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 102,
      descripcion: 'Manufactura de otros productos alimenticios',
      codigoActividadEconomica: 'D029',
      codigoCIIU: 102,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.73',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 115,
      descripcion: 'Manufactura de otros productos minerales no metálicos.',
      codigoActividadEconomica: 'D28',
      codigoCIIU: 115,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.743',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 124,
      descripcion: 'Manufactura de otros tipo de equipos de transporte',
      codigoActividadEconomica: 'D46',
      codigoCIIU: 124,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.747',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 125,
      descripcion: 'Manufactura de papel y productos de papel',
      codigoActividadEconomica: 'D48',
      codigoCIIU: 125,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.717',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 105,
      descripcion: 'Manufactura de productos de vestir',
      codigoActividadEconomica: 'D08',
      codigoCIIU: 105,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.733',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 117,
      descripcion:
        'Manufactura de productos metálicos, excepto maquinaria y equipo',
      codigoActividadEconomica: 'D32',
      codigoCIIU: 117,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.713',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 104,
      descripcion: 'Manufactura de productos textiles',
      codigoActividadEconomica: 'D06',
      codigoCIIU: 104,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.74',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 123,
      descripcion:
        'Manufactura de vehículos automotores, remolques y semirremolques',
      codigoActividadEconomica: 'D44',
      codigoCIIU: 123,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.61',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 22,
      descripcion: 'Melón',
      codigoActividadEconomica: 'A0213101',
      codigoCIIU: 22,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.603',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 15,
      descripcion: 'Ñame, ñampí y tiquizque',
      codigoActividadEconomica: 'A021154',
      codigoCIIU: 15,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.857',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 206,
      descripcion: 'Operativa  de fondos de inversión',
      codigoActividadEconomica: 'J06',
      codigoCIIU: 206,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.14',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 283,
      descripcion: 'Operativa de fondos de inversión y de pensión',
      codigoActividadEconomica: 'Y22',
      codigoCIIU: 283,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.86',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 207,
      descripcion: 'Operativa de planes de pensión',
      codigoActividadEconomica: 'J08',
      codigoCIIU: 207,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.857',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 205,
      descripcion: 'Operativa de Seguros',
      codigoActividadEconomica: 'J04',
      codigoCIIU: 205,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.13',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 282,
      descripcion: 'Operativa de Seguros',
      codigoActividadEconomica: 'Y20',
      codigoCIIU: 282,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.98',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 247,
      descripcion:
        'Otras actividades conexas a servicio y asesoría de informática',
      codigoActividadEconomica: 'R229',
      codigoCIIU: 247,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.14',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 284,
      descripcion: 'Otras actividades de asistencia social',
      codigoActividadEconomica: 'Y24',
      codigoCIIU: 284,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.183',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 295,
      descripcion:
        'Otras actividades de la Administración Pública no contempladas en las anteriores',
      codigoActividadEconomica: 'Y909',
      codigoCIIU: 295,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.84',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 192,
      descripcion: 'Otras actividades de transporte de turistas',
      codigoActividadEconomica: 'I0232',
      codigoCIIU: 192,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.867',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 215,
      descripcion: 'Otras actividades empresariales',
      codigoActividadEconomica: 'K90',
      codigoCIIU: 215,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.613',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 26,
      descripcion: 'Otras frutas',
      codigoActividadEconomica: 'A0213190',
      codigoCIIU: 26,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.623',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 32,
      descripcion:
        'Otras plantas utilizables para preparar bebidas y alimentos',
      codigoActividadEconomica: 'A0213390',
      codigoCIIU: 32,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.843',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 195,
      descripcion: 'Otro tipo de transporte automotor',
      codigoActividadEconomica: 'I029',
      codigoCIIU: 195,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.603',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 16,
      descripcion: 'Otros  granos  comestibles y verduras',
      codigoActividadEconomica: 'A021190',
      codigoCIIU: 16,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.993',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 253,
      descripcion: 'Otros  servicios',
      codigoActividadEconomica: 'R90',
      codigoCIIU: 253,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.633',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 42,
      descripcion: 'Otros cultivos',
      codigoActividadEconomica: 'A02189',
      codigoCIIU: 42,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.82',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 177,
      descripcion: 'Otros de comercio',
      codigoActividadEconomica: 'G90',
      codigoCIIU: 177,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.71',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 100,
      descripcion: 'Otros productos de molinería',
      codigoActividadEconomica: 'D0259',
      codigoCIIU: 100,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.063',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 265,
      descripcion: 'Otros rubros de consumo',
      codigoActividadEconomica: 'S90',
      codigoCIIU: 265,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.943',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 234,
      descripcion: 'Otros servicios de  salud',
      codigoActividadEconomica: 'R049',
      codigoCIIU: 234,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.913',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 223,
      descripcion: 'Otros servicios de enseñanza y actividades conexas',
      codigoActividadEconomica: 'M90',
      codigoCIIU: 223,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.62',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 30,
      descripcion: 'Palma aceitera',
      codigoActividadEconomica: 'A0213302',
      codigoCIIU: 30,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.62',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 31,
      descripcion: 'Palmito',
      codigoActividadEconomica: 'A0213303',
      codigoCIIU: 31,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.6',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 12,
      descripcion: 'Papa',
      codigoActividadEconomica: 'A021151',
      codigoCIIU: 12,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.95',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 240,
      descripcion: 'Peluquería, maquillaje y  actividades  conexas',
      codigoActividadEconomica: 'R16',
      codigoCIIU: 240,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.673',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 72,
      descripcion: 'Pesca (detallado)',
      codigoActividadEconomica: '',
      codigoCIIU: 72,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.68',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 77,
      descripcion: 'Pesca de otros animales',
      codigoActividadEconomica: 'B068',
      codigoCIIU: 77,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.613',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 24,
      descripcion: 'Piña',
      codigoActividadEconomica: 'A0213103',
      codigoCIIU: 24,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.69',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 85,
      descripcion:
        'Preparación y enriquecimiento de minerales y actividades de servicios conexas',
      codigoActividadEconomica: 'C06',
      codigoCIIU: 85,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.05',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 260,
      descripcion: 'Préstamos para  educación parauniversitaria',
      codigoActividadEconomica: 'S10',
      codigoCIIU: 260,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.057',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 261,
      descripcion: 'Préstamos para eduación universitaria',
      codigoActividadEconomica: 'S12',
      codigoCIIU: 261,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.057',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 262,
      descripcion:
        'Préstamos para otras modalidades de educación o capacitación',
      codigoActividadEconomica: 'S14',
      codigoCIIU: 262,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.723',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 110,
      descripcion: 'Producción de artículos de paja y de materiales trenzables',
      codigoActividadEconomica: 'D18',
      codigoCIIU: 110,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.72',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 108,
      descripcion:
        'Producción de madera y fabricación de productos de madera y corcho, excepto muebles',
      codigoActividadEconomica: 'D14',
      codigoCIIU: 108,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.76',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 134,
      descripcion:
        'Producción y suministro de   gas, vapor y agua caliente y actividades de servicios conexas',
      codigoActividadEconomica: 'E04',
      codigoCIIU: 134,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.76',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 133,
      descripcion:
        'Producción y suministro de electricidad y actividades de servicios conexas',
      codigoActividadEconomica: 'E02',
      codigoCIIU: 133,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.697',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 90,
      descripcion:
        'Producción, procesamiento y conservación de carne de ganado porcino',
      codigoActividadEconomica: 'D0212',
      codigoCIIU: 90,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.697',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 89,
      descripcion:
        'Producción, procesamiento y conservación de carne de ganado vacuno',
      codigoActividadEconomica: 'D0211',
      codigoCIIU: 89,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.7',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 92,
      descripcion:
        'Producción, procesamiento y conservación de carne de otro tipo de animales',
      codigoActividadEconomica: 'D0214',
      codigoCIIU: 92,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.7',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 91,
      descripcion: 'Producción, procesamiento y conservación de carne de pollo',
      codigoActividadEconomica: 'D0213',
      codigoCIIU: 91,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.947',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 239,
      descripcion: 'Publicidad',
      codigoActividadEconomica: 'R14',
      codigoCIIU: 239,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.75',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 127,
      descripcion: 'Reciclaje',
      codigoActividadEconomica: 'D52',
      codigoCIIU: 127,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.76',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 135,
      descripcion:
        'Recolección, purificación y distribución de agua  y actividades de servicios conexas',
      codigoActividadEconomica: 'E06',
      codigoCIIU: 135,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.727',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 112,
      descripcion:
        'Refinamiento de petróleo, combustible nuclear y fabricación de coque.',
      codigoActividadEconomica: 'D22',
      codigoCIIU: 112,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.797',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 159,
      descripcion: 'Reparación de  vivienda',
      codigoActividadEconomica: 'F0415',
      codigoCIIU: 159,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.933',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 227,
      descripcion: 'Reparación de electrodomésticos',
      codigoActividadEconomica: 'R022',
      codigoCIIU: 227,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.783',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 152,
      descripcion: 'Reparación de inmuebles',
      codigoActividadEconomica: 'F024',
      codigoCIIU: 152,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.933',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 228,
      descripcion: 'Reparación de otros  bienes',
      codigoActividadEconomica: 'R029',
      codigoCIIU: 228,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.027',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 258,
      descripcion: 'Reparación de vehículos',
      codigoActividadEconomica: 'S06',
      codigoCIIU: 258,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.93',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 226,
      descripcion: 'Reparación de vehículos de motor y motocicletas',
      codigoActividadEconomica: 'R021',
      codigoCIIU: 226,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.827',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 184,
      descripcion: 'Restaurante',
      codigoActividadEconomica: 'H04',
      codigoCIIU: 184,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.863',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 210,
      descripcion:
        'Resto de actividades auxiliares de intermediación financiera',
      codigoActividadEconomica: 'J109',
      codigoCIIU: 210,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.073',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 273,
      descripcion: 'Salud',
      codigoActividadEconomica: 'Y02',
      codigoCIIU: 273,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.613',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 25,
      descripcion: 'Sandía',
      codigoActividadEconomica: 'A0213104',
      codigoCIIU: 25,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.097',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 276,
      descripcion: 'Seguridad',
      codigoActividadEconomica: 'Y08',
      codigoCIIU: 276,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.94',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 233,
      descripcion: 'Servicio clínico veterinario y actividades conexas',
      codigoActividadEconomica: 'R044',
      codigoCIIU: 233,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.977',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 244,
      descripcion: 'Servicio de internet',
      codigoActividadEconomica: 'R221',
      codigoCIIU: 244,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.91',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 221,
      descripcion: 'Servicios de apoyo a la educación',
      codigoActividadEconomica: 'M10',
      codigoCIIU: 221,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.06',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 263,
      descripcion: 'Servicios médicos',
      codigoActividadEconomica: 'S16',
      codigoCIIU: 263,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.667',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 67,
      descripcion:
        'Silvicultura (reforestación) y actividades de servicio conexas',
      codigoActividadEconomica: 'A101',
      codigoCIIU: 67,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.593',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 9,
      descripcion: 'Sorgo',
      codigoActividadEconomica: 'A021105',
      codigoCIIU: 9,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.597',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 10,
      descripcion: 'Soya',
      codigoActividadEconomica: 'A021106',
      codigoCIIU: 10,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.633',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 41,
      descripcion: 'Tabaco',
      codigoActividadEconomica: 'A02182',
      codigoCIIU: 41,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.017',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 256,
      descripcion: 'Tarjetas de crédito.',
      codigoActividadEconomica: 'S02',
      codigoCIIU: 256,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.107',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 278,
      descripcion: 'Telecomunicaciones',
      codigoActividadEconomica: 'Y12',
      codigoCIIU: 278,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.763',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 136,
      descripcion: 'Telecomunicaciones y actividades de servicios conexas',
      codigoActividadEconomica: 'E08',
      codigoCIIU: 136,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.677',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 75,
      descripcion: 'Tilapia',
      codigoActividadEconomica: 'B063',
      codigoCIIU: 75,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.94',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 232,
      descripcion: 'Trabajo social',
      codigoActividadEconomica: 'R043',
      codigoCIIU: 232,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.087',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 275,
      descripcion: 'Transporte',
      codigoActividadEconomica: 'Y06',
      codigoCIIU: 275,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.847',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 198,
      descripcion: 'Transporte  ferroviario',
      codigoActividadEconomica: 'I08',
      codigoCIIU: 198,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.843',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 197,
      descripcion: 'Transporte aéreo',
      codigoActividadEconomica: 'I06',
      codigoCIIU: 197,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.83',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 188,
      descripcion: 'Transporte de carga',
      codigoActividadEconomica: 'I021',
      codigoCIIU: 188,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.833',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 189,
      descripcion: 'Transporte de estudiantes',
      codigoActividadEconomica: 'I022',
      codigoCIIU: 189,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.85',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 200,
      descripcion: 'Transporte de turistas (por cualquier medio)',
      codigoActividadEconomica: 'I12',
      codigoCIIU: 200,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.843',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 196,
      descripcion: 'Transporte marítimo y de cabotaje',
      codigoActividadEconomica: 'I04',
      codigoCIIU: 196,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.84',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 194,
      descripcion: 'Transporte público (Autobús)',
      codigoActividadEconomica: 'I025',
      codigoCIIU: 194,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.84',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 193,
      descripcion: 'Transporte público (Taxi)',
      codigoActividadEconomica: 'I024',
      codigoCIIU: 193,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.83',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 187,
      descripcion: 'Transporte terrestre automotor',
      codigoActividadEconomica: 'I02',
      codigoCIIU: 187,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.15',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 287,
      descripcion: 'Turismo',
      codigoActividadEconomica: 'Y30',
      codigoCIIU: 287,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.817',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 176,
      descripcion: 'Venta al detalle de combustible automotriz',
      codigoActividadEconomica: 'G08',
      codigoCIIU: 176,
    },
    {
      fechaCreacion: '2016-07-17T05:50:07.06',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 264,
      descripcion: 'Viaje',
      codigoActividadEconomica: 'S18',
      codigoCIIU: 264,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.973',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 242,
      descripcion: 'Vigilancia y seguridad',
      codigoActividadEconomica: 'R20',
      codigoCIIU: 242,
    },
    {
      fechaCreacion: '2016-07-17T05:50:06.6',
      usuarioCreacion: 'JP6024CP',
      fechaModificacion: null,
      usuarioModificacion: null,
      idActividadEconomica: 13,
      descripcion: 'Yuca',
      codigoActividadEconomica: 'A021152',
      codigoCIIU: 13,
    },
  ];
}
